name: Full-Stack Image Compressor Tool

push:
    branches: [ "main", "sub-main" ]
    paths:
      - "ImageApp/**"
      - "ImageCompressor/**"
      - ".github/workflows/ci.yml"
      
  pull_request:
    branches: [ "main", "sub-main" ]
    paths:
      - "ImageApp/**"
      - "ImageCompressor/**"
      - ".github/workflows/ci.yml"

  workflow_dispatch:

permissions:
  contents: read


jobs:
  frontend-build:
    name: Frontend Build - Node
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show frontend structure
        run: |
          pwd
          ls -la
          ls -la ImageApp

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: npm
          cache-dependency-path: ImageApp/package-lock.json

      - name: Install frontend dependencies
        run: npm ci
        working-directory: ImageApp

      - name: Build frontend
        run: npm run build
        working-directory: ImageApp
        
  backend-build:
    name: Backend Build - Spring Boot Maven
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show backend structure
        run: |
          pwd
          ls -la
          ls -la ImageCompressor

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
          cache-dependency-path: ImageCompressor/pom.xml

      - name: Build backend with Maven
        run: mvn -B -f ImageCompressor/pom.xml clean verify

      - name: Upload backend JAR
        uses: actions/upload-artifact@v4
        with:
          name: backend-jar
          path: ImageCompressor/target/*.jar
